### ISSUE TITLE
Sundials KLU linear solver

### ISSUE THREAD

**Issue by martinjrobins** [Chris00/sundials-sys#3]
I'm interested in using the Sundials KLU linear solver (https://sundials.readthedocs.io/en/latest/sunlinsol/SUNLinSol_links.html#the-sunlinsol-klu-module). I had a look and couldn't see a feature to enable this, so I assume this has not been implemented? Note that  it would require linking against suitesparse (https://github.com/DrTimothyAldenDavis/SuiteSparse)

I would be happy to work on this issue and make a PR

**Comment by Chris00** [comment]
Thanks for your interest in these bindings.  You are very welcome to propose a PR to make the KLU solver available under a feature gate.

You may also be interested in the [higher level interface](https://github.com/Chris00/rust-sundials) even though it is in early stage of development and an interface to linear solvers hasn't yet been implemented.  (A generic one, as is now available for vectors, will be written — albeit not in the coming month as I will not have enough time.)

**Comment by martinjrobins** [comment]
Thanks @Chris00, the rust wrapper is looking good, I'll certainly keep an eye on this. I should say that I'm also developing a ODE/DAE solver library in rust (https://github.com/martinjrobins/diffsol), so I'll look into using your higher level interface as a way of incorportating the sundials solvers in there. Be great to work out how we can work together on this rather than duplicating effort!

**Comment by Chris00** [comment]
> Be great to work out how we can work together on this rather than duplicating effort!

I agree.  I haven't had time to have a real look at your project yet but maybe we can chat one of these days to understand better how we can collaborate?

**Comment by Chris00** [comment]
Fixed by [version 0.5](https://crates.io/crates/sundials-sys/0.5.0).
