### ISSUE TITLE
Using `gh`, I was alerted to the origin repository 

### ISSUE THREAD

**Issue by CGMossa** [Chris00/sundials-sys#4]
Lovely package. I'm getting into it! 

One thing I quickly noticed: 

```sh
! Repository krtab/sundials-sys set as the default repository. To learn more about the default repository, run: gh repo set-default --help
```

**Comment by Chris00** [comment]
I'm not using `gh`.  May you be clearer ?  @krtab Any clue?

**Comment by CGMossa** [comment]
Oh. I don't think this is anything serious, maybe it is a setting on github that needs to be changed. Running the suggested command: 
```sh
This command sets the default remote repository to use when querying the
GitHub API for the locally cloned repository.

gh uses the default repository for things like:

 - viewing and creating pull requests
 - viewing and creating issues
 - viewing and creating releases
 - working with GitHub Actions
 - adding repository and environment secrets

USAGE
  gh repo set-default [<repository>] [flags]

FLAGS
  -u, --unset   unset the current default repository
  -v, --view    view the current default repository
```

I believe `gh` is basically just a CLI for GitHub, so what it says, is more or less what the github API contains.

I don't know the implication of this, nor do I know where to change this (unless of course an owner uses the commands suggested by `gh`).

**Comment by krtab** [comment]
I'm afraid there isn't much to do, and this is a limitation of `gh` itself.

The "fork history" of this repo is https://github.com/jasondark/sundials-sys -> https://github.com/krtab/sundials-sys -> https://github.com/Chris00/sundials-sy. If you use `gh` to clone this repo, you'll see the message you mention, but funnily enough, if you clone my fork, you'll see a message telling you that @jasondark's repo was set as the default.

I didn't find any setting on my repo to somehow indicate that @Chris00's fork is now the "upstream", so I guess this is rather a bug/enhancement to take to the `gh` or github UI team.

**Comment by CGMossa** [comment]
Sorry, I thought I was helping out. If this is the case, then allow me to close this..

If it is okay, I have a few more of these issues, that I'll raise.. But I'll try to be more thorough.
